#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\PageController::index
  methods: GET

display_characters:
  path: /character/{id}
  controller: App\Controller\PageController::displayCharacter
  methods: GET
