#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\PageController::index
  methods: GET

display_characters:
  path: /displayCharacters
  controller: App\Controller\PageController::displayCharacters
  methods: GET
